### ISSUE TITLE
Support for v0.8.7

### ISSUE THREAD

**Issue by camilonova** [fernandokosh/redmine_time_tracker#1]
Hi, great tool, can you get this working for v0.8.7?

**Comment by delaitre** [comment]
I tried the plugin on redmine 0.8.7.

On a functional point of view it is working (you just have to comment the "requires_redmine :version_or_higher => '0.9.0'" in "init.rb".

However, the localized strings aren't working, some icons are missing with 0.8.7, and the menu entry is not at the correct position (which is not really a problem).

I will try to see why localized strings aren't working as this is really "user unfriendly".
Icons should not be a real problem, I'll look at it too.

**Comment by delaitre** [comment]
I have created a 0.1 branch for Redmine 0.8.2+ and a 0.2 branch for 0.9.0+.

**Comment by camilonova** [comment]
Thanks, i just install and migrate the plugin and works like charm.

Great work
