### ISSUE TITLE
Add license to plugin

### ISSUE THREAD

**Issue by huerlisi** [fernandokosh/redmine_time_tracker#11]
Hi

Thank you a lot for this nice plugin!

While I'm quite sure you published this plugin as open source, it's not clear under which license. It probably would make sense to use GPL (as Redmine), MIT (as Ruby and Rails), or AGPL (like GPL but also affects hosted instances).

By convention you should add a file named COPYRIGHT.txt mentioning the License and (A)GPL.txt containing the original license text. See http://github.com/edavis10/redmine-customer-plugin for an example.

Thank you again, and sorry for bothering you with boring legal stuff, but it's what makes open source so powerfull;-)

Kind regards
Simon

**Comment by delaitre** [comment]
You are right, I will do that as soon as the time permit :)

**Comment by delaitre** [comment]
Well, it takes me more time to right this response than it takes me to add these files...
