### ISSUE TITLE
error on admin panel when no trackers

### ISSUE THREAD

**Issue by ghost** [fernandokosh/redmine_time_tracker#14]
A ActionView::TemplateError occurred in time_trackers#index:

 undefined method `count' for []:Array
 On line #4 of vendor/plugins/redmine_time_tracker/app/views/time_trackers/index.rhtml

   1: <h2><%= l(:time_tracker_admin_title) %></h2>
   2:
   3: <div class="time-tracker-admin">
   4:     <% if @time_trackers.count > 0 %>
   5:         <div class="autoscroll">
   6:             <table class="list">
   7:                 <thead>

   vendor/plugins/redmine_time_tracker/app/views/time_trackers/index.rhtml:4:in `_run_rhtml_vendor47plugins47redmine_time_tracker47app47views47time_trackers47index46rhtml'
   passenger (2.2.4) lib/phusion_passenger/rack/request_handler.rb:91:in`process_request'
   passenger (2.2.4) lib/phusion_passenger/abstract_request_handler.rb:206:in `main_loop'
   passenger (2.2.4) lib/phusion_passenger/railz/application_spawner.rb:376:in`start_request_handler'
   passenger (2.2.4) lib/phusion_passenger/railz/application_spawner.rb:334:in `handle_spawn_application'
   passenger (2.2.4) lib/phusion_passenger/utils.rb:182:in`safe_fork'

Changing line 4 to the following fixes:
<% if ! @time_trackers.empty? %>

This is on redmine r3683

**Comment by delaitre** [comment]
This is fixed in master. Thanks!
