### ISSUE TITLE
Associate role with viewing the current time trackers

### ISSUE THREAD

**Issue by kralux** [fernandokosh/redmine_time_tracker#16]
Right now, it seems that only users with admin privilege are able to see the current time trackers.
There should be a permission for this that could be associated with any role. 
This way, say a manager who is not an admin could look at the trackers.

Could you please let me know when you might be able to implement this feature if ever?

Thanks a lot for a GREAT plugin. This is the best one!

Cheers,

Alex

**Comment by delaitre** [comment]
Well, the "Time trackers" page was made only (in the first place) to let the admin delete the "zombies" time trackers if needed.
It is simple to add a permission to be able to view this page and even a permission to be able to delete other users trackers. So if I will implement this, it should be done quickly.
However, I did not know if this is a good idea. This feature sounds to me like if the boss of a company wants to scrutinize every seconds of his employees (big brother is watching you, you know :D).
However, I can imagine that the admin of a big company has better to do than deleting zombie time trackers!
The thing is zombie time trackers will be displayed when I will implement issue #8 (I mean, when the user will see his trackers, he will be able to delete his own zombies). Thus, the current "Time trackers" page will become useless unless you are big brother...
Can I ask why you need someone to be able to see this page?

**Comment by delaitre** [comment]
http://www.redmine.org/boards/3/topics/12026?r=18404 explains a good use case for this feature.

**Comment by delaitre** [comment]
This is available in master (SHA: fc95986d133a55ac09ecf1f4581b024f83e80bdf)
