### ISSUE TITLE
plugin preventing login

### ISSUE THREAD

**Issue by Batist** [fernandokosh/redmine_time_tracker#19]
This is a repost from this issue: http://www.redmine.org/issues/5550

"After installing the redmine_time_tracker plugin users that are not already logged in cannot login. see attach image with 2 login 'boxes'." (link to the image: http://www.redmine.org/attachments/3790/redmine_login.png)

**Comment by MischaTheEvil** [comment]
I'm not able to reproduce this error using the current Redmine trunk and with the latest version of the plugin.
I've also tested it with the theme you use in the screenshots (classic), but still not able to reproduce...

Can you post the precise steps to reproduce and the precise environment in which the error occurs (including browser)?

**Comment by ghost** [comment]
same here. i see sometimes "2 login" forms and at this time it's impossible to login.
cannot describe steps to reproduce it.
it happen from time to time...

**Comment by Batist** [comment]
I updated the plugin, now the error seems to be gone. (I guess this makes the downloadable plugin needs to be updated?)

Thanks! Nice plugin btw!
