### ISSUE TITLE
Redmine 0.9.4 - Login Page & My Account Page have alterations after installation

### ISSUE THREAD

**Issue by joshsten** [fernandokosh/redmine_time_tracker#20]
After applying this plugin in Redmine 0.9.4.  The Login page duplicates itself, and the My Account page moves the Sidebar to the top after a short delay of 5-10 seconds. Removing the plugin fixes the issue. I am researching the issue cause.

**Comment by delaitre** [comment]
This seems to duplicate issue #4 which is fixed in the master branch. Feel free to reopen a bug report if that's not the case.
