### ISSUE TITLE
no such file to load -- rubygems / cannot install

### ISSUE THREAD

**Issue by L0HENGRIN** [fernandokosh/redmine_time_tracker#22]
Hi there,

I have installed redmine 1.0.1-0 with the bitnami stack / native installer 
http://bitnami.org/stack/redmine#nativeInstaller 
on my Kubuntu 10.04 Linux System, wich all run fine.

Then i tried to install that plugin redmine_time_tracker. Therefore I followed the instructions on http://www.redmine.org/wiki/redmine/Plugins 
But when it comes to the point where to "rake db:migrate_plugins RAILS_ENV=production", it gives the following error:

admin1@fsc:~/redmine-1.0.1-0/apps/redmine$ rake db:migrate_plugins
 (in /home/admin1/redmine-1.0.1-0/apps/redmine)
rake aborted!
no such file to load -- rubygems
/home/admin1/redmine-1.0.1-0/apps/redmine/Rakefile:4:in `require'
(See full trace by running task with --trace)

I logged into redmine - no plugin.
I restarted redmine - "Internal Server Error"
I deleted /vendor/plugins/redmine_time_tracker  and restarted redmine - it runs like before, no errors.

As i am very new to ruby at all, i really do not understand what is going wrong here. 
Any help would be appreciated.

**Comment by delaitre** [comment]
Well, I've not tested the plugin on a redmine 1.0.x and I've no free time for this right now. However, even if you successfully install the plugin, you should be subject to the bug #15 as you use a bitnami stack (which use sub-url).

I don't know how redmine 1.0.x changed plugins and if some adjustments are needed (obviously it requires some changes...).

**Comment by L0HENGRIN** [comment]
ok thanks for your help. i wil try to install redmine by hand next days. i would like to see your plugin in action :)  - thx, domger

**Comment by L0HENGRIN** [comment]
Hi again. I solved my problem totally. Here is -in short- how i successfully installed the PlugIn into the bitnami redmine-1.0.1-0 stack:

I downloaded the PlugIn and moved to: ~/redmine-1.0.1-0/apps/redmine/vendor/plugins
then:
cd ~/redmine-1.0.1-0/apps/redmine/vendor/plugins
mv delaitre-redmine_time_tracker-4d88a5d redmine_time_tracker
rm -rf delaitre-redmine_time_tracker-0.2.0-0-g0798f13.tar.gz
cd ~
cd redmine-1.0.1-0/
./use_redmine

rake db:migrate_plugins RAILS_ENV=production
exit
sh ctlscript.sh restart

then:
Logged into Redmine as an Administrator

And voilà ! it is up and running!
Thx Jérémie for that absolutely useful PlugIn ! I missed that so much :)
thx!
-domger

**Comment by delaitre** [comment]
As you use a bitnami stack, you need to execute the "use_redmine" script in order to let the system find all ruby tools (like rake). This probably was your problem.

**Comment by L0HENGRIN** [comment]
Yes, indeed.
