### ISSUE TITLE
Integrate with Redmine's default time tracking system

### ISSUE THREAD

**Issue by knoopx** [fernandokosh/redmine_time_tracker#23]
I like the idea and implementation of this plugin however I use both ways of logging time and there's no way of aggregating data from both locations.

**Comment by delaitre** [comment]
I didn't understand the problem. The plugin use the redmine time tracking system. What it does is simply to fill the "log time" entry of the redmine form when you stop the time tracker. Then, it's like when you click on "log time" link and enter the value by hand.

**Comment by delaitre** [comment]
No update on this so I close it.
