### ISSUE TITLE
Standalone Window + enter issue number

### ISSUE THREAD

**Issue by davidb2002** [fernandokosh/redmine_time_tracker#32]
Firstly, really great tool! Making my life loads easier.

One annoyance is that I have to stay in redmine to use the logger. I would be nice if you could have the option to open the logger in a new window. Along with that, a way to manually enter an issue number in this new window. That way there isn't any need to go into redmine apart from logging in and initiating the timetracker.

**Comment by delaitre** [comment]
I don't know if I understood what you want correctly.

It seems that you want an application which allow you to enter an issue number and a start/stop button. If this is what you want, the better way to do this is probably to write a whole new application which uses the redmine REST API (I don't now if the current REST API allow to add new timelog). Indeed, you can even do a multi-platform application which do this, or one for your handset or whatever.

The most important part of the redmine_time_tracker plugin is not the start/stop logic but the whole rails controllers/views stuff. Thus, it doesn't make sense to reuse it for a standalone application.

I close this issue as I will not implement it. However, feel free to post a comment if I misunderstood something.

**Comment by davidb2002** [comment]
You understood me compeltly and yes the API would ideally be the way to go. However, i think development is still way off for that. I just felt that as you have the whole start/stop thing nailed on, why not have an option to open it in a new window too thus making it a bit easier to use. The added features would allow users to use it without much need to going into redmine and this would make the time tracker much more useful.

**Comment by delaitre** [comment]
I don't see the benefit of your solution. At the moment you have a window with redmine which displays the time tracker (which is needed to know the issue number you will work on). You want a window which displays only the time tracker. The later is still a window which displays webpage but with less information. Thus, I don't see any benefit and this is why I'm wondering if I really understand what you want :)
