### ISSUE TITLE
Not context button for start/stop

### ISSUE THREAD

**Issue by timir0n** [fernandokosh/redmine_time_tracker#36]
Hello, could you create just a link(button or image, etc.) at issue details view to start/stop time tracker.

The reason why it's need is that usually i go into issue details and leave details open until task completed. So, it would be good to have start button there.
We have more then 200 tasks active in the same time, so working with context menu is annoying sometimes.

**Comment by delaitre** [comment]
There is a start/stop link in the top menu (next to account information). Indeed, the context menu was added later!

If I misunderstood the problem, feel free to leave a comment.

**Comment by timir0n** [comment]
ok. Looks like I can't find it.
here is screenshot
http://img408.imageshack.us/img408/5623/trackerc.png

**Comment by timir0n** [comment]
ok. I found it. closed.
