### ISSUE TITLE
Home page problem

### ISSUE THREAD

**Issue by camilonova** [fernandokosh/redmine_time_tracker#4]
Hi,

when you're at the home page and wait about 10 seconds, it executes a javascript function and loads the entire content of the page, again, in the account div, 

See it here http://i40.tinypic.com/m832ur.jpg 
This is the generated html http://pastebin.com/FjG8qPHU

Thanks, im using redmine 0.9.3 but happens me also in 0.8.x

**Comment by jomey** [comment]
I solved this issue, by putting the contents of app/views/time_tracker/_update_menu.rhtml in a condition:
 <% if !@project.nil? %>
  CONTENTS_OF_UPDATE_MENU.HTML
 <% end %>

I also reduced the interval for updates from 5 to 60 seconds. One update per minute is sufficient for my tracking purposes.
_update_menu.rhtml
#29: <%= javascript_tag "new PeriodicalExecuter(updateTimeTrackerMenu, 60);" %>

**Comment by delaitre** [comment]
fgrehm send me a pull request which fix this more cleanly. I will pull it soon.
http://github.com/fgrehm/redmine_time_tracker

**Comment by greenmang0** [comment]
@jomey - thanks for the solution
