### ISSUE TITLE
Missing action buttons

### ISSUE THREAD

**Issue by tina-junold** [fernandokosh/redmine_time_tracker#46]
Hello,

After install an migrate the plugin i started using it, but i have no stop/pause button.
I don't know where the problem could be... try it by your self: projects.ideaplexus.com demouser:demouser

**Comment by delaitre** [comment]
Hmmm, strange. When I go to your site, there is no CSS at all (just some links on a white background, and when I click on a link, I got an empty page). Don't know if this is the problem you mentionned ?

If this is not the problem (i.e. it works fine for you...) you need to add the "log time" permission to the users (and probably assign to the users a role for a project which has log time capabilities too).

**Comment by tina-junold** [comment]
Mmh, sometimes my apache runs unstable (on an ubuntu lts o_O) the site works now fine...
I've added the user to the "engineer" role. This group has these capabilities.
Please retry by yourself

**Comment by delaitre** [comment]
Ok it works.
I think the problem comes from the plugin's CSS (and images) not beeing retrieved by the client properly. All the icons (pause/resume/stop in the top menu, the running clock, the icons in the context menu of the issue list) are missing.
I already had this problem with an old redmine version 0.9.<something> but I got no trouble with this now.
Which redmine version do you use ?

**Comment by tina-junold** [comment]
Im using redmine from a ppa:
https://launchpad.net/~ondrej/+archive/redmine
maybe its not the best way to set up redmine, but it's much more simple

**Comment by delaitre** [comment]
This seems to be redmine 1.1.0 which should be fine...
Looking in the redmine's log should give some information on what's going on (maybe you'll need to run redmine in developpement environment. I can't tell you how to to that with your redmine install however...)

**Comment by delaitre** [comment]
I just tried with the latest redmine 1.2.0 and it works fine. This should really be a problem in your configuration/system.
