### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by beebase** [fernandokosh/redmine_time_tracker#54]
I'm getting this error when trying to start a time tracker.
Can any one give me a pointer?
Thanks.

(great plugin btw)

---

Processing TimeTrackersController#start (for 83.80.249.221 at 2011-05-10 00:13:26) [POST]
  Parameters: {"issue_id"=>"318", "action"=>"start", "authenticity_token"=>"cccccccc=", "controller"=>"time_trackers"}

NoMethodError (undefined method `time_spent=' for #<TimeTracker:0x3f1b7a8>):
  vendor/plugins/redmine_time_tracker/app/models/time_tracker.rb:21:in`initialize'
  vendor/plugins/redmine_time_tracker/app/controllers/time_trackers_controller.rb:18:in `new'
  vendor/plugins/redmine_time_tracker/app/controllers/time_trackers_controller.rb:18:in`start'

Rendering /Applications/stackRedmine/apps/redmine/public/500.html (500 Internal Server Error)

**Comment by martin-denizet** [comment]
Are you sure you migrated your database properly?
```cd /var/www/redmine
RAILS_ENV=production rake db:migrate_plugins

```
```

**Comment by beebase** [comment]
I did a clean install after discovering other issues with database. All working ok since then.
Please close.
Thanks.
