### ISSUE TITLE
Cant report minutes

### ISSUE THREAD

**Issue by camilonova** [fernandokosh/redmine_time_tracker#60]
Hey, great plugin there :)

I cant report times like: 1.23 or 0.20 redmine only takes the integer part, i try to search all over but no one has this problem.

i have done all migrations and i have the latest plugin version and Redmine 1.2.1.stable (PostgreSQL)

Thanks for your help

**Comment by delaitre** [comment]
This is strange as with the plugin I do this all the time!
Moreover, as the plugin uses the redmine's own page to log the time (all the
plugin does is to pre-fill the "log time" text field for you) this should
work. If it doesn't then it's probably a redmine bug.

**Comment by camilonova** [comment]
Thanks i will fill the bug for redmine, your plugin works like charm :D
