### ISSUE TITLE
After starting tracking, it displays time spend and issue but stop/pause action

### ISSUE THREAD

**Issue by denizcan** [fernandokosh/redmine_time_tracker#68]
Mine works as stated until I started the tracker on an issue. It counts up however does not display stop/pause action like it was stated.. I cannot stop the tracker and complete the tracking process..

**Comment by denizcan** [comment]
I found other things:
- In Windows XP Explorer, it does not show stop and trackers buttons, however to the right of the time spent there are active areas linked to /time_trackers and /time_trackers/stop..
- In Mac Safari and Chrome, it does not either display or have active areas.
- I can stop timer by manually entering /time_trackers/stop to the URL..

**Comment by denizcan** [comment]
It also does not update the time spend automatically. I had to refresh the page..

**Comment by delaitre** [comment]
Well, this does a lot of things :)

First things first: which versions of the plugin (0.4, master branch, ...?) and of Redmine do you use?

**Comment by denizcan** [comment]
0.4 master branch, Redmine 1.2.2.stable..

**Comment by delaitre** [comment]
Well, 0.4 is not master :)

This seems quite similar to #46 and #59.

**Comment by denizcan** [comment]
By master I mean I checked out the link given, didn't changed the branch..

**Comment by denizcan** [comment]
Ok, per #59 I solved the problem..

I created plugin_assets in public path of redmine, and linked assets path as redmine_time_tracker directory as in that path..

**Comment by delaitre** [comment]
Ok. I close this issue then.

**Comment by denizcan** [comment]
I think you should put this info to installation text, until it is resolved for every situation..

**Comment by delaitre** [comment]
Good idea, I've updated the README :)
