### ISSUE TITLE
ChiliProject support

### ISSUE THREAD

**Issue by brodock** [fernandokosh/redmine_time_tracker#71]
Hi, I know the name says "redmine" time tracker, but as Chili Project is a fork and have similar codebase, it should be easy to adapt redmine time tracker to work as well on Chili Project, could you please check it?

**Comment by delaitre** [comment]
Indeed, I use the plugin with Chili Project. However, it requires some fixes mainly due to the Chili Project theme layout which is not "compatible".

The easiest way to be compatible with Chili Project or other Redmine theme would be to add a plugin setting allow to indicate in (or before/after) which HTML div the time tracker should be placed.

In the end, however, I think the code base of Chili Project and Redmine would split more and more and the plugins will certainly be incompatible between the two projects.

**Comment by rpeters4beardon** [comment]
Might I ask a bit more direction on what changes needed to be made, or at least the files that needed to be touched to get it working?  We're trying to use it with Chiliproject as well, and just need a general pointer as to where to look.

Thanks.

**Comment by delaitre** [comment]
Well, it appears that our sys admin (which has done the ChiliPorject 'fix') is quite overburdened at the moment. I'll try to get our 'fixed' version of the plugin from him as soon as he have a little bit of free time.

**Comment by pprkut** [comment]
Is there any update on this? I would really like to have this running on chiliproject

**Comment by delaitre** [comment]
As I mentioned in #79, I don't quite know how to support ChiliProject properly now that Redmine 2.0 is out.
We use ChiliProject here so I don't have much interest in Redmine 2.0 support. However, it will be sad to drop Redmine support as this is still "redmine_time_tracker"!

Maybe the way to go is to fork the project and have a "chiliproject_time_tracker". The thing is there seems to be a very interesting fork adding lot of features to the plugin. Thus, forking will prevent to have those easily.

In the end, Redmine and ChiliProject will probably be a lot different and thus, we will need a plugin for each. This is already the case indeed with the new default style of ChiliProject, the Rails3 dependency of Redmine 2.x...

**Comment by pprkut** [comment]
I do see the issue there and I agree that over time chiliproject and redmine will most likely diverge.
However, the rails3 dependency shouldn't be an issue for long as the next major chiliproject version will use it too.

Maybe you could have the chiliproject code in a separate branch for now? Just an idea

**Comment by tvdeyen** [comment]
I vote for an extra ChiliProject plugin.

I forked and will submit some patches.

**Comment by tvdeyen** [comment]
https://github.com/magiclabs/ChiliProject-TimeTracker

**Comment by tvdeyen** [comment]
I made some changes and moved the time tracker menu to the left sidebar.
This was the best place I could found for now. There aren't that much places a plugin developer can hook in.
Please test my fork and tell me what you think.
