### ISSUE TITLE
Not compatible with Redmine 1.4.0

### ISSUE THREAD

**Issue by cassianomonteiro** [fernandokosh/redmine_time_tracker#73]
When installing with Redmine 1.4.0, got this error:

Showing vendor/plugins/redmine_time_tracker/app/views/time_trackers/_embed_menu.rhtml where line #52 raised: 
No route matches {:controller=>"time_trackers", :action=>"index"}

49: 
50: <% if User.current.allowed_to?(:log_time, nil, :global => true) or User.current.allowed_to?(:view_others_time_trackers, nil, :global => true) %>
51:     <span>
52:         <%= link_to '',
53:             { :controller => 'time_trackers', :action => 'index' },
54:             { :class => 'icon-action icon-list-action', :title => l(:list_time_trackers) }
55:         %>

**Comment by cassianomonteiro** [comment]
I created the file config/routes.rb with the following contents:

ActionController::Routing::Routes.draw do |map|
  map.connect 'time_trackers', :controller => 'time_trackers', :action => 'index'
  map.connect 'time_trackers', :controller => 'time_trackers', :action => 'render_menu'
  map.connect 'time_trackers', :controller => 'time_trackers', :action => 'start'
end

But still there are lots of problems on trying to use the plugin.

**Comment by delaitre** [comment]
This seems to duplicate #70 which is fixed (in current development version). Feel free to reopen this bug if I'm wrong.

**Comment by cassianomonteiro** [comment]
Sorry, I didn't search for another issues... Thanks!
