### ISSUE TITLE
About assets not showing (403) (RESOLVED)

### ISSUE THREAD

**Issue by stephanebachelier** [fernandokosh/redmine_time_tracker#80]
You should change permission for every file in plugin_assets/redmine_time_tracker/[images | javascripts | stylesheets] to have a read permissions for others, like a chmod o+r on each file.

$ cd <redmine_root>/public/plugin_assets/redmine_time_tracker
$ find -type f -print0 | xargs -0 chmod o+r

Regards,

**Comment by delaitre** [comment]
I've just tried to do a fresh clone of the repository and all files in the "assets" directory (and sub-directories) have read permissions for everyone.

If I remember correctly, the "plugin_assets" directory is where we have to copy the plugin asset files for them to be found by redmine. However, this is done by hand so I don't know what can be down at the plugin level to "fix" this.

**Comment by stephanebachelier** [comment]
If permissions are right in the plugin assets dir then nothing should be done, as copy files to plugin_assets should not modify file permissions. But maybe I'm wrong.

No matters, it is only a small annoyance that may already be fixed. 
Anyway great plugin, really useful.
