### ISSUE TITLE
Dead Timetrack - not removable

### ISSUE THREAD

**Issue by xstable** [fernandokosh/redmine_time_tracker#88]
I have a dead Timetrack in my redmine and I'm not able to delete or finish it.

![screenshot_003_20140311](https://f.cloud.github.com/assets/1778068/2386003/e531d8d4-a925-11e3-822e-502dc16e2d39.jpg)

The message above in English is this: The Time is less or equals NULL. Thats not permitted.

How can i remove this Entry?

**Comment by fernandokosh** [comment]
What version of plugin and redmine are you using?
Also, did you see any error in  the logs? Can you show me?

**Comment by xstable** [comment]
0.9.5
Which Logs do you mean? Where can i find them?

**Comment by fernandokosh** [comment]
The App Logs. You can find it at /path/to/redmine/log/production.log or development.log. If you are running on Linux, you can run these command to see:

$ tailf log/production.log

Then, reload the time tracker page. Please post only relevant block.

I will do a clean Redmine 0.9.5 install to try to see the error. Please send me all installed Gems and their versions.
